apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgresql-service
  name: postgresql-service
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: postgresql