apiVersion: v1
kind: ConfigMap
metadata:
  name: AnalyticsConfigMap
data:
  DB_NAME: dtq-project4
  DB_USER: postgres
  DB_HOST: <ENTER YOUR DB HOST HERE>
  DB_PORT: <ENTER YOUR DB PORT HERE>
---
apiVersion: v1
kind: Secret
metadata:
  name: <NAME OF THE Secret>
type: Opaque
data:
  <THE KEY FROM Secret WHICH has THE ENCODED PASSWORD>: <OUTPUT OF `echo -n 'the password' | base64`>